Repository aykutkardas/regexlearn.com, pull requests merged in 2021-11, with the labels that each got.

#34 fix: every key press changing language when focus language globe
  src/components/LanguageSwitch/index.jsx
Labels: bug

#37 Fix negative lookbehind code in cheatsheet
  src/cheatsheet.json
Labels: typo

#42 Update EN and TR localization
  src/localization/en-us.json
  src/localization/tr-tr.json
Labels: typo

#44 Fix: `steps.rangeNumber.title` for `en-us`
  src/localization/en-us.json
Labels: typo

#45 fix typo in lesson 52
  src/localization/en-us.json
Labels: typo

#55 Fix typo at footer
  src/components/Footer/index.jsx
Labels: typo

#57 [Learn]: Clarify braces vs brackets
  src/localization/en-us.json
Labels: typo, learn

#65 Fix Asterisk Typo
  src/cheatsheet.json
  src/data.json
  src/localization/en-us.json
  src/localization/tr-tr.json
Labels: typo, learn

#71 Feature/prettier
  .prettierrc
Labels: development

#75 Fix typo in line 17 and 58
  src/localization/tr-tr.json
Labels: typo, learn
